// swift-tools-version: 6.2

import Foundation
import PackageDescription

let package = Package(
    name: "manis",
    defaultLocalization: "en",
    platforms: [
        .macOS("26.0"),
    ],
    products: [
        .executable(name: "manis", targets: ["manis"]),
        .executable(name: "MainXPC", targets: ["MainXPC"]),
        .executable(name: "MainDaemon", targets: ["MainDaemon"]),
    ],
    dependencies: [
        .package(url: "https://github.com/jpsim/Yams", from: "6.2.0"),
        .package(url: "https://github.com/Square/Valet", from: "5.0.0"),
        .package(url: "https://github.com/ChimeHQ/Rearrange", from: "2.0.0"),
        .package(url: "https://github.com/ra1028/DifferenceKit", from: "1.3.0"),
        .package(url: "https://github.com/apple/swift-system", from: "1.6.3"),
        .package(url: "https://github.com/CharlesJS/SwiftyXPC", from: "0.5.4"),
        .package(url: "https://github.com/trilemma-dev/SecureXPC", from: "0.8.0"),
        .package(url: "https://github.com/dfed/swift-async-queue", from: "1.0.1"),
        .package(url: "https://github.com/apple/swift-algorithms", from: "1.2.1"),
        .package(url: "https://github.com/apple/swift-http-types", from: "1.5.1"),
        .package(url: "https://github.com/apple/swift-collections", from: "1.3.0"),
        .package(url: "https://github.com/krzyzanowskim/STTextView", from: "2.2.6"),
        .package(url: "https://github.com/SFSafeSymbols/SFSafeSymbols", from: "7.0.0"),
        .package(url: "https://github.com/siteline/swiftui-introspect", from: "26.0.0"),
        .package(url: "https://github.com/apple/swift-async-algorithms", from: "1.1.0"),
        .package(url: "https://github.com/pointfreeco/swift-tagged", from: "0.10.0"),
        .package(url: "https://github.com/pointfreeco/swift-sharing", from: "2.7.4"),
        .package(url: "https://github.com/pointfreeco/swift-nonempty", from: "0.5.0"),
        .package(url: "https://github.com/pointfreeco/swift-perception", from: "2.0.9"),
        .package(url: "https://github.com/pointfreeco/swift-navigation", from: "2.6.0"),
        .package(url: "https://github.com/pointfreeco/swift-case-paths", from: "1.7.2"),
        .package(url: "https://github.com/pointfreeco/swift-dependencies", from: "1.10.0"),
        .package(url: "https://github.com/pointfreeco/swift-concurrency-extras", from: "1.3.2"),
        .package(url: "https://github.com/pointfreeco/swift-identified-collections", from: "1.1.1"),
        .package(url: "https://github.com/pointfreeco/swift-composable-architecture", from: "1.23.1"),
    ],
    targets: [
        .executableTarget(
            name: "manis",
            dependencies: [
                .product(name: "Yams", package: "Yams"),
                .product(name: "Rearrange", package: "Rearrange"),
                .product(name: "Collections", package: "swift-collections"),
                .product(name: "ComposableArchitecture", package: "swift-composable-architecture"),
                .product(name: "SwiftUIIntrospect", package: "swiftui-introspect"),
                .product(name: "Dependencies", package: "swift-dependencies"),
                .product(name: "Perception", package: "swift-perception"),
                .product(name: "CasePaths", package: "swift-case-paths"),
                .product(name: "IdentifiedCollections", package: "swift-identified-collections"),
                .product(name: "Sharing", package: "swift-sharing"),
                .product(name: "SwiftNavigation", package: "swift-navigation"),
                .product(name: "ConcurrencyExtras", package: "swift-concurrency-extras"),
                .product(name: "STTextView", package: "STTextView"),
                .product(name: "Tagged", package: "swift-tagged"),
                .product(name: "NonEmpty", package: "swift-nonempty"),
                .product(name: "SystemPackage", package: "swift-system"),
                .product(name: "Valet", package: "Valet"),
                .product(name: "Algorithms", package: "swift-algorithms"),
                .product(name: "AsyncAlgorithms", package: "swift-async-algorithms"),
                .product(name: "HTTPTypes", package: "swift-http-types"),
                .product(name: "HTTPTypesFoundation", package: "swift-http-types"),
                .product(name: "DifferenceKit", package: "DifferenceKit"),
                .product(name: "SFSafeSymbols", package: "SFSafeSymbols"),
                .product(name: "AsyncQueue", package: "swift-async-queue"),
                .product(name: "SwiftyXPC", package: "SwiftyXPC"),
            ],
            path: "manis",
            exclude: [
                "XPC",
                "Daemon",
                "Supporting Files/Info.plist",
                "manis.entitlements",
            ],
            resources: [
                .process("Resources"),
            ],
            swiftSettings: [
                .swiftLanguageMode(.v6),
                .enableUpcomingFeature("StrictConcurrency"),
                .enableUpcomingFeature("ApproachableConcurrency"),
            ],
        ),
        .executableTarget(
            name: "MainXPC",
            dependencies: [
                .product(name: "SecureXPC", package: "SecureXPC"),
            ],
            path: "manis/XPC",
            exclude: [
                "com.manis.XPC.plist",
            ],
            swiftSettings: [
                .swiftLanguageMode(.v6),
                .enableUpcomingFeature("StrictConcurrency"),
                .enableUpcomingFeature("ApproachableConcurrency"),
            ],
        ),
        .executableTarget(
            name: "MainDaemon",
            dependencies: [
                .product(name: "Yams", package: "Yams"),
                .product(name: "ConcurrencyExtras", package: "swift-concurrency-extras"),
                .product(name: "SystemPackage", package: "swift-system"),
                .product(name: "Algorithms", package: "swift-algorithms"),
                .product(name: "AsyncAlgorithms", package: "swift-async-algorithms"),
                .product(name: "AsyncQueue", package: "swift-async-queue"),
            ],
            path: "manis/Daemon",
            exclude: [
                "MainDaemon.entitlements",
                "Info.plist",
                "Launchd.plist",
            ],
            swiftSettings: [
                .swiftLanguageMode(.v6),
                .enableUpcomingFeature("StrictConcurrency"),
                .enableUpcomingFeature("ApproachableConcurrency"),
            ],
        ),
    ],
)
